apiVersion: apps/v1
kind: Deployment
metadata:
  name: gra-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gra
  template:
    metadata:
      labels:
        app: gra
    spec:
      containers:
      - name: gra
        image: basialx/tetris:latest
        ports:
        - containerPort: 80
